name: docs/gh-pages
on:
  create:
    tags:
      - v*

jobs:
    build-docs:
        name: Build docs and push to gh-pages
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Setup python 
              uses: actions/setup-python@master
              with:
                python-version: 3.8
            
            - name: Install poetry
              uses: snok/install-poetry@v1
              with:
                version: 1.1.10
                virtualenvs-create: true
                virtualenvs-in-project: true

            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
            
            - name: Install dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root

            - name: Install library
              run: poetry install --no-interaction
            
            - name: build docs
              run: |
                source .venv/bin/activate
                cd docs
                make clean
                make html
                cd ..
            
            - name: deploy to gh-pages
              uses: Cecilapp/GitHub-Pages-deploy@master
              env:
                EMAIL: dhagan@mit.edu
                GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BUILD_DIR: docs/_build/html